### ISSUE TITLE
Removed from the Chrome Web Store?

### ISSUE THREAD

**Issue by zxjinn** [nsa-yoda/ContextDeleter#9]
The [Chrome store URL](https://chrome.google.com/webstore/detail/contextdeleter/cdagpkhlnpefnkemlbcolbfjokjhgcda?hl=en-US) in your README returns a 404 ☹️ 

In my browser (Chrome 103) the extension was automatically disabled recently and says it violated Chrome Web Store policy (see image below)

What happened? I use this extension multiple times a day! Your competitors are all terrible, this is the one true extension.

Do you think it's from the most recent code change in #8? [This page](https://chrome-stats.com/d/cdagpkhlnpefnkemlbcolbfjokjhgcda) says it was removed the last day in June.

---

![image](https://user-images.githubusercontent.com/1184723/178890317-c3ccbb02-7ad5-4e47-83a9-828de7bc76cf.png)

**Comment by SpyShadow117** [comment]
Sense Chrome Store removed it. I just downloaded a release/master copy and added it manually to chrome extensions. When in the extensions menu, enable developer mode, click on load unpacked and select the extracted folder of files.

Of course doing this means your loading what ever is in the files, if only I knew the reason on why the extension was removed, it's a good extension I use daily.

**Comment by jsanc623** [comment]
I just saw this @SpyShadow117 and @zxjinn - I've been busy with other projects (mainly [Sphire](https://github.com/sphireinc)) and this project, unfortunately, fell by the wayside. 

The project was delisted by Google from the Chrome Store because I requested permissions that Google deemed not necessary, yet I couldn't in the few short times I tried to update the application find a way to get it to work without the necessary permissions.

Rejection notice from Chrome Developer Dashboard: 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1890716/205428271-d9fa5367-e6c1-4594-a684-94da5ff51838.png">
 
For the record, as noted in [`https://github.com/jsanc623/ContextDeleter/blob/master/manifest.json`](https://github.com/jsanc623/ContextDeleter/blob/master/manifest.json#L8), the permissions I request for the extension are: 

    "contextMenus",
    "tabs",
    "storage"
 
 
 I'll have to dedicate some time in the future to going through Google's new permissions documentation and requirements and figuring out a way to get it to work so it can be republished in the Chrome Store. For now, as @SpyShadow117 mentioned, you can side load the extension with the release/master copy in developer mode. 
 
 The code is fairly simple, and the majority of the code lies within `content.js`, `background.js`, and `options.js`

**Comment by zxjinn** [comment]
Not expecting a reply, just an update. I sideloaded the extension on a new computer today and got this error in the Extensions page. The ContextDeleter extension still works, but in the future (if they ever get rid of V2) it looks like that won't be true. 

😢 

![image](https://user-images.githubusercontent.com/1184723/236051420-f2cce7f1-2b59-492d-b6bc-93d01ec87ac4.png)

**Comment by nsa-yoda** [comment]
@zxjinn @SpyShadow117 I've submitted a new version of this to review today, hopefully gets re-listed in the extension store
